testMajster/TestMaster/urls.py
# TestMajster/TestMaster/urls.py

from django.urls import path
from . import views
from .views import test_cases_list

app_name = 'TestMaster'

urlpatterns = [
    path('', views.index, name='index'),  # The root path for listing test cases
    path('new/', views.new_test_case, name='new_test_case'),  # The path for the new test case form
    path('test-cases/', views.test_cases_list, name='test-cases-list'),
    # path('test-case/detail/<int:pk>/', views.test_case_detail, name='test-case-detail'),
    path('test-case/edit/<int:pk>/', views.test_case_edit, name='test-case-edit'),
]

testMajster/testMajster/urls.py
# testMajster/urls.py
from django.contrib import admin
from django.urls import include, path
from TestMaster import views  # Import the views from TestMaster app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),  # Root URL to show index view from TestMaster
    path('TestMaster/', include('TestMaster.urls')),  # Include TestMaster app URLs
]

testMajster/TestMaster/models.py
from django.db import models


# Define the TestCase model
class TestCase(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    # Assume you have fields for status and expected_result here as well
    status = models.CharField(max_length=50, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('In Progress', 'In Progress')])
    expected_result = models.TextField()

    def __str__(self):
        return self.title


# Define the TestStep model which relates to TestCase
class TestStep(models.Model):
    test_case = models.ForeignKey(TestCase, related_name='test_steps', on_delete=models.CASCADE)
    step_description = models.TextField()
    expected_result = models.TextField()

    def __str__(self):
        return f"Step for {self.test_case.title}: {self.step_description}"

# Remember to add 'TestMaster' to the INSTALLED_APPS setting in settings.py
# After updating your models

testMajster/TestMaster/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import TestCase, TestStep


class TestCaseForm(forms.ModelForm):
    class Meta:
        model = TestCase
        fields = ['title', 'description', 'status', 'expected_result']


# Define the form for individual test steps
class TestStepForm(forms.ModelForm):
    class Meta:
        model = TestStep
        fields = ['step_description', 'expected_result']  # Assuming these are the fields on your TestStep model


# Create a formset for test steps related to a test case
TestStepFormSet = inlineformset_factory(
    parent_model=TestCase,
    model=TestStep,
    form=TestStepForm,
    extra=1,
    can_delete=True
)

testMajster/TestMaster/views.py
# TestMaster/views.py
import form
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse

from .forms import TestCaseForm
from .models import TestCase


def index(request):
    test_cases = TestCase.objects.all()  # Get all test cases from the database
    return render(request, 'TestMaster/index.html', {'test_cases': test_cases})


def new_test_case(request):
    if request.method == 'POST':
        form = TestCaseForm(request.POST)
        if form.is_valid():
            test_case = form.save()
            return redirect('TestMaster:test_cases_list')
    else:
        form = TestCaseForm()
    return render(request, 'TestMaster/new_test_case.html', {'form': form})


def test_cases_list(request):
    test_cases = TestCase.objects.all().order_by('id')
    return render(request, 'TestMaster/test_cases_list.html', {'test_cases': test_cases})


def test_case_detail(request, pk):
    test_case = get_object_or_404(TestCase, pk=pk)
    test_steps = test_case.test_steps.all()  # Use the correct related_name
    return render(request, 'TestMaster/test_case_detail.html', {'test_case': test_case, 'test_steps': test_steps})


def test_case_edit(request, pk):
    test_case = get_object_or_404(TestCase, pk=pk)
    if request.method == 'POST':
        form = TestCaseForm(request.POST, instance=test_case)
        if form.is_valid():
            form.save()
            return redirect('TestMaster:test-cases-list')
    else:
        form = TestCaseForm(instance=test_case)

    context = {'form': form}
    return render(request, 'TestMaster/test_case_edit.html', context)

testMajster/TestMaster/templates/TestMaster/index.html
<!-- TestMajster/TestMaster/templates/TestMaster/index.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>Test Cases</h2>
  <ul>
    {% for test_case in test_cases %}
      <li>
        {{ test_case.id }} - {{ test_case.title }}
        <p>New test case has been added.</p>
      </li>
    {% empty %}
      <li>No test cases available.</li>
    {% endfor %}
  </ul>
{% endblock %}

testMajster/TestMaster/templates/TestMaster/new_test_case.html
{% extends 'base.html' %}

{% block content %}
<h2>Create a New Test Case</h2>
<form method="post" id="test-case-form">
    {% csrf_token %}
    {{ form.as_p }}
    <table id="steps-table">
        <thead>
        <tr>
            <th>Step</th>
            <th>Description</th>
            <th>Result</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <!-- Step rows will be inserted here by JavaScript -->
        </tbody>
    </table>
    <button type="submit">Save Test Case</button>
</form>

<script>
    let stepCount = 0;

    function addStep(belowElement = null) {
        const tableBody = document.querySelector("#steps-table tbody");
        const rowIndex = belowElement ? Array.from(tableBody.children).indexOf(belowElement) + 1 : tableBody.children.length;
        const newRow = tableBody.insertRow(rowIndex);

        newRow.className = "step-row";
        newRow.setAttribute("data-step-index", rowIndex + 1);

        const cellStep = newRow.insertCell(0);
        cellStep.className = "step-num";
        cellStep.textContent = "Step " + (rowIndex + 1);

        const cellDesc = newRow.insertCell(1);
        const inputDesc = document.createElement("input");
        inputDesc.type = "text";
        inputDesc.name = "step_description_" + (rowIndex + 1);
        inputDesc.placeholder = "Description";
        cellDesc.appendChild(inputDesc);

        const cellResult = newRow.insertCell(2);
        const inputResult = document.createElement("input");
        inputResult.type = "text";
        inputResult.name = "step_result_" + (rowIndex + 1);
        inputResult.placeholder = "Result";
        cellResult.appendChild(inputResult);

        const cellActions = newRow.insertCell(3);
        const addButton = document.createElement("button");
        addButton.type = "button";
        addButton.textContent = "Add Step";
        addButton.onclick = function() { addStep(newRow); };
        cellActions.appendChild(addButton);

        const removeButton = document.createElement("button");
        removeButton.type = "button";
        removeButton.textContent = "Remove";
        removeButton.onclick = function() { removeStep(newRow); };
        cellActions.appendChild(removeButton);

        updateStepNumbers();
    }

    function removeStep(row) {
        const tableBody = document.querySelector("#steps-table tbody");
        tableBody.removeChild(row);
        updateStepNumbers();
    }

    function updateStepNumbers() {
        const allStepRows = document.querySelectorAll("#steps-table .step-row");
        allStepRows.forEach((row, index) => {
            const stepNumber = index + 1;
            row.setAttribute("data-step-index", stepNumber);
            row.querySelector(".step-num").textContent = "Step " + stepNumber;
            row.querySelector("input[name^='step_description_']").name = "step_description_" + stepNumber;
            row.querySelector("input[name^='step_result_']").name = "step_result_" + stepNumber;
        });
        stepCount = allStepRows.length;
    }

    // Initially add the first step on page load
    document.addEventListener('DOMContentLoaded', function() {
    addStep(); // This will add the first step row
});
</script>
{% endblock %}

testMajster/TestMaster/templates/TestMaster/test_case_detail.html
<!-- path/filename: testmaster/templates/testmaster/test_case_detail.html -->
{% extends 'base.html' %}

{% block content %}
<h2>Test Case Details</h2>
<!-- ... display other test case details ... -->

<h3>Steps:</h3>
<ol>
    {% for step in test_case.steps.all %}
    <li>
        <strong>Description:</strong> {{ step.description }}
        <strong>Result:</strong> {{ step.result }}
        <h1>dupa</h1>
    </li>
    {% empty %}
    <li>No steps added.</li>
    {% endfor %}
</ol>

<!-- ... rest of your template ... -->
{% endblock %}

testMajster/TestMaster/templates/TestMaster/test_case_edit.html
<!-- test_case_edit.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Edit Test Case</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>
{% endblock %}

testMajster/TestMaster/templates/TestMaster/test_cases_list.html
{% extends 'base.html' %}

{% block content %}
<h2>Test Cases List</h2>
<table>
    <thead>
        <tr>
            <th><strong>ID</strong></th>
            <th>Title</th>
            <th>Status</th>
            <!-- Add more headers if needed -->
        </tr>
    </thead>
    <tbody>
        {% for test_case in test_cases %}
        <tr>
            <td>{{ test_case.id }}</td>
            <td><a href="{% url 'TestMaster:test-case-edit' test_case.id %}">{{ test_case.title }}</a></td>
            <td>{{ test_case.status }}</td>
        </tr>
        {% endfor %}

    </tbody>
</table>
{% endblock %}

testMajster/TestMaster/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TestMajster</title>
    <style>
        body { margin: 0; font-family: Arial, sans-serif; }
        .top-bar { background-color: #333; color: white; text-align: center; padding: 10px 0; }
        .sidebar { background-color: #f2f2f2; width: 200px; position: fixed; height: 100%; top: 0; left: 0; }
        .sidebar a { display: block; padding: 10px; text-decoration: none; color: black; }
        .sidebar a:hover { background-color: #ddd; }
        .content { margin-left: 200px; padding: 20px; }
        @media (max-width: 600px) {
            .sidebar { width: 100%; height: auto; position: relative; }
            .content { margin-left: 0; }
        }
    </style>
</head>
<body>
    <div class="top-bar">
        <h1>TestMajster</h1>
    </div>
    <div class="sidebar">
        <a href="{% url 'TestMaster:test-cases-list' %}">Test Cases</a>
        <a href="{% url 'TestMaster:new_test_case' %}">New Test Case</a>
        <!-- Add other links as needed -->
    </div>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>